### PR TITLE
testing gatsby v4 alpha

### PR DESCRIPTION
**Pull request by rmatambo8**
Hi!
In case you didn’t know, Gatsby is planning its next major version for Q4 of this year! In preparation, the Gatsby team is reaching out to maintainers for our most popular Starters to help make the upgrade to Gatsby 4 as smooth as possible.
This PR updates your Gatsby Starter to the alpha version of this next release, as well as some related plugins. It’s just in draft form for now, since the 4.0.0 version of Gatsby isn’t quite ready for release yet. We’re mainly testing updating Gatsby and the other official plugins to ensure that the Starter builds without errors.
You may see some warnings from packages that list gatsby: ^3.0.0 as a peer dependency (Don’t worry, we’ll come back and fix those before we take this PR out of draft mode when it’s ready to be merged).
If you have any questions / concerns, let us know in the comments. Thanks again for all your work as a Gatsby maintainer. We’re so grateful to have you as part of our community 💜
For more information on what’s coming with Gatsby v4, check out: gatsbyjs/gatsby#32860

Changes:
- migrated packages to v4 alpha
- changed react import style to * as React
- removed gatsby-image to prefer gatsby plugin image(no longer in use)

some thinks noted:
 - images don't show up on artwork page, seems like an issue that was there before update
Screen Shot 2021-09-02 at 9 44 44 AM

### CODE REVIEW

**Comment by kalwalt** [comment]
Thank you @rmatambo8 for this! Unfortunately i have not so much time to support you for now, but i hope in the middle of september to have more  free time to help and review.

**Comment by rmatambo8** [comment]
No worries, I'll keep you posted as i go along!

**Comment by kalwalt** [comment]
Hi @rmatambo8 i merged PR #149 maybe you can update with the latest. 
About the images, it works for me, i mean i can see the images. But they are hosted on [picsum](https://i.picsum.photos/id/1015/6000/4000.jpg), can you verify if they are loaded or not?

**Comment by kalwalt** [comment]
> Hi @rmatambo8 i merged PR #149 maybe you can update with the latest.
> About the images, it works for me, i mean i can see the images. But they are hosted on [picsum](https://picsum.photos/id/1015/6000/4000.jpg), can you verify if they are loaded or not?

I opened an issue #158 i will fix when i have time.

**Comment by kalwalt** [comment]
i fixed the issue of the images see #158 and there are recent changes merged in the master branch. Netlify build fails because gatsby v4.0 require node >=14.15.0 but the [.nvmrc](https://github.com/kalwalt/gatsby-starter-i18n-bulma/blob/master/.nvmrc) file require "12.18.1". I think that upgrading will solve the issue.

**Comment by rmatambo8** [comment]
that sounds promising, I'm gonna follow up on what you said and then get back to you.

**Comment by kalwalt** [comment]
> that sounds promising, I'm gonna follow up on what you said and then get back to you.

Perfect let me know if you have other questions/issues! By the way, there so many conflicts because @MartinRosenberg changed the component extensions to.jsx.

**Comment by kalwalt** [comment]
Closing this because https://github.com/kalwalt/gatsby-starter-i18n-bulma/pull/189 is merged on master branch.
Thank you @rmatambo8 for your help!

**Pull request closed without merging**
