### PR TITLE
Amp feature

### PR DESCRIPTION
**Pull request by kalwalt**
adding amp to the home page

### CODE REVIEW

**Comment by kalwalt** [comment]
The Amp/amp.sass style library is too big for Amp. I should develop a small library not based on bulma (or the problem is sass?)....

**Comment by kalwalt** [comment]
I'm  workin on the css re-styling, most of the works to strip too large libs (Bulma, animate.css...) that are in the project.

**Comment by kalwalt** [comment]
I still receive these errors in the Amp validate tool:

```js
CSS syntax error in tag 'style amp-custom' - saw invalid at rule '@charset'.AUTHOR_STYLESHEET_PROBLEM
line 1, column 1059
  
The author stylesheet specified in tag 'style amp-custom' is too long - document contains 145754 bytes whereas the limit is 50000 bytes.AUTHOR_STYLESHEET_PROBLEM
line 1, column 1059
  
Custom JavaScript is not allowed.CUSTOM_JAVASCRIPT_DISALLOWED
line 29, column 11386
  
The attribute 'disable-session-states' in tag 'amp-accordion' is set to the invalid value 'true'.DISALLOWED_HTML
line 29, column 18384
```
The work for tomorrow and after...

**Comment by kalwalt** [comment]
i still receive the `custom javscript not allowed` error but the amp page is now correct.

**Comment by JOduMonT** [comment]
AMP project is dead: https://www.google.com/search?q=amp+is+dead

**Comment by kalwalt** [comment]
Thanks to report this. One more reason to close this PR, haven't worked from a while because wasn't able to solve some issues.

**Pull request closed without merging**
