### PR TITLE
Multi nested menu feature

### PR DESCRIPTION
**Pull request by kalwalt**
As pointed out in the previous PR #91  and in the #92 i think i will enhance the dropdown menu: i have to figure out how to modify the existent dropdown menu for the multi menu feature. The problem is that the artwork menu is injected with the list of all the menus, how can i attach another one in the node needed?
As in the issue #92 my reference is this example code: https://codepen.io/sakthig/pen/RvwVYM?editors=1100
my DropdownMenu component: 
   
```html
     <div className="navbar-item has-dropdown is-hoverable">
       <Link className="navbar-link" to={props.base}>
         <FaImage className="menu-names" />
         <FormattedMessage id={props.baseName} />
       </Link>
       <div className="navbar-dropdown is-hidden-mobile is-boxed">
       {switches &&( switches.map(( message ) => (
         <Link className="navbar-item" key={message} to={links[message][sel]}>
           <FormattedMessage id={message} />
         </Link>
        )))}
       </div>
     </div>
```
from the listed example:

 ```html
<div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <div class="nested navbar-item dropdown">
            <div class="dropdown-trigger">
              <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
      <span>Dropdown button</span>
      <span class="icon is-small">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <a href="#" class="dropdown-item">
        Dropdown item
      </a>
                <a class="dropdown-item">
        Other dropdown item
      </a>
                <a href="#" class="dropdown-item is-active">
        Active dropdown item
      </a>
                <a href="#" class="dropdown-item">
        Other dropdown item
      </a>
                <hr class="dropdown-divider">
        <div class="nested dropdown dropdown-item">
            <div class="dropdown-trigger">
              <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
      <span>Dropdown button</span>
      <span class="icon is-small">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
   </button>
            </div>
```

### CODE REVIEW

**Comment by kalwalt** [comment]
i found this resource https://github.com/Wikiki/bulma-calendar/blob/master/demo/index.html i think it will help me a lot

**Comment by kalwalt** [comment]
The prodcution build process fails! error attached:

```javascript
walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$ gatsby build
success open and validate gatsby-configs — 0.012 s
success load plugins — 0.905 s
success onPreInit — 0.005 s
success delete html and css files from previous builds — 0.006 s
success initialize cache — 0.012 s
success copy gatsby files — 0.022 s
success onPreBootstrap — 0.015 s
success source and transform nodes — 0.452 s
success building schema — 0.530 s
success createPages — 0.134 s
success createPagesStatefully — 0.062 s
success onPreExtractQueries — 0.002 s
success update schema — 0.049 s
success extract queries from components — 0.459 s
success run static queries — 0.058 s — 2/2 35.09 queries/second


success run page queries — 1.185 s — 43/43 36.31 queries/second
success write out page data — 0.005 s
success write out redirect data — 0.001 s

success onPostBootstrap — 0.000 s

info bootstrap finished - 7.227 s


gatsby-plugin-purgecss: Only processing  /home/walter/kalwalt-github/gatsby-starter-i18n-bulma/src/components/all.sass
success Building production JavaScript and CSS bundles — 56.826 s
 
gatsby-plugin-purgecss:
 Previous CSS Size: 344.87 KB
 New CSS Size: 183.39 KB (-46.82%)
 Removed ~161.48 KB of CSS


error Building static HTML failed

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

> 1 | !function webpackUniversalModuleDefinition(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.bulmaCollapsible=t():e.bulmaCollapsible=t()}(window,function(){return function(e){var t={};function __webpack_require__(n){if(t[n])return t[n].exports;var r=t[n]={i:n,l:!1,exports:{}};return e[n].call(r.exports,r,r.exports,__webpack_require__),r.l=!0,r.exports}return __webpack_require__.m=e,__webpack_require__.c=t,__webpack_require__.d=function(e,t,n){__webpack_require__.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},__webpack_require__.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},__webpack_require__.t=function(e,t){if(1&t&&(e=__webpack_require__(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(__webpack_require__.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var r in e)__webpack_require__.d(n,r,function(t){return e[t]}.bind(null,r));return n},__webpack_require__.n=function(e){var t=e&&e.__esModule?function getDefault(){return e.default}:function getModuleExports(){return e};return __webpack_require__.d(t,"a",t),t},__webpack_require__.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},__webpack_require__.p="",__webpack_require__(__webpack_require__.s=12)}([function(e,t){function _getPrototypeOf(t){return e.exports=_getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function _getPrototypeOf(e){return e.__proto__||Object.getPrototypeOf(e)},_getPrototypeOf(t)}e.exports=_getPrototypeOf},function(e,t){e.exports=function _classCallCheck(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}},function(e,t){function _defineProperties(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}e.exports=function _createClass(e,t,n){return t&&_defineProperties(e.prototype,t),n&&_defineProperties(e,n),e}},function(e,t){e.exports=function _assertThisInitialized(e){if(void 0===e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return e}},function(e,t,n){var r=n(8);e.exports=function _objectSpread(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{},o=Object.keys(n);"function"==typeof Object.getOwnPropertySymbols&&(o=o.concat(Object.getOwnPropertySymbols(n).filter(function(e){return Object.getOwnPropertyDescriptor(n,e).enumerable}))),o.forEach(function(t){r(e,t,n[t])})}return e}},function(e,t,n){var r=n(6),o=n(3);e.exports=function _possibleConstructorReturn(e,t){return!t||"object"!==r(t)&&"function"!=typeof t?o(e):t}},function(e,t){function _typeof2(e){return(_typeof2="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function _typeof2(e){return typeof e}:function _typeof2(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}function _typeof(t){return"function"==typeof Symbol&&"symbol"===_typeof2(Symbol.iterator)?e.exports=_typeof=function _typeof(e){return _typeof2(e)}:e.exports=_typeof=function _typeof(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":_typeof2(e)},_typeof(t)}e.exports=_typeof},function(e,t,n){var r=n(11);e.exports=function _inherits(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function");e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,writable:!0,configurable:!0}}),t&&r(e,t)}},function(e,t){e.exports=function _defineProperty(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}},function(e,t,n){n(0);var r=n(10);function _get(t,n,o){return"undefined"!=typeof Reflect&&Reflect.get?e.exports=_get=Reflect.get:e.exports=_get=function _get(e,t,n){var o=r(e,t);if(o){var i=Object.getOwnPropertyDescriptor(o,t);return i.get?i.get.call(n):i.value}},_get(t,n,o||t)}e.exports=_get},function(e,t,n){var r=n(0);e.exports=function _superPropBase(e,t){for(;!Object.prototype.hasOwnProperty.call(e,t)&&null!==(e=r(e)););return e}},function(e,t){function _setPrototypeOf(t,n){return e.exports=_setPrototypeOf=Object.setPrototypeOf||function _setPrototypeOf(e,t){return e.__proto__=t,e},_setPrototypeOf(t,n)}e.exports=_setPrototypeOf},function(e,t,n){"use strict";n.r(t);var r=n(1),o=n.n(r),i=n(2),s=n.n(i),l=n(5),a=n.n(l),c=n(3),u=n.n(c),f=n(0),p=n.n(f),_=n(9),d=n.n(_),h=n(7),y=n.n(h),v=n(4),b=n.n(v),m=function(){function EventEmitter(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:[];o()(this,EventEmitter),this._listeners=new Map(e),this._middlewares=new Map}return s()(EventEmitter,[{key:"listenerCount",value:function listenerCount(e){return this._listeners.has(e)?this._listeners.get(e).length:0}},{key:"removeListeners",value:function removeListeners(){var e=this,t=arguments.length>0&&void 0!==arguments[0]?arguments[0]:null,n=arguments.length>1&&void 0!==arguments[1]&&arguments[1];null!==t?Array.isArray(t)?name.forEach(function(t){return e.removeListeners(t,n)}):(this._listeners.delete(t),n&&this.removeMiddleware(t)):this._listeners=new Map}},{key:"middleware",value:function middleware(e,t){var n=this;Array.isArray(e)?name.forEach(function(e){return n.middleware(e,t)}):(Array.isArray(this._middlewares.get(e))||this._middlewares.set(e,[]),this._middlewares.get(e).push(t))}},{key:"removeMiddleware",value:function removeMiddleware(){var e=this,t=arguments.length>0&&void 0!==arguments[0]?arguments[0]:null;null!==t?Array.isArray(t)?name.forEach(function(t){return e.removeMiddleware(t)}):this._middlewares.delete(t):this._middlewares=new Map}},{key:"on",value:function on(e,t){var n=this,r=arguments.length>2&&void 0!==arguments[2]&&arguments[2];if(Array.isArray(e))e.forEach(function(e){return n.on(e,t)});else{var o=(e=e.toString()).split(/,|, | /);o.length>1?o.forEach(function(e){return n.on(e,t)}):(Array.isArray(this._listeners.get(e))||this._listeners.set(e,[]),this._listeners.get(e).push({once:r,callback:t}))}}},{key:"once",value:function once(e,t){this.on(e,t,!0)}},{key:"emit",value:function emit(e,t){var n=this,r=arguments.length>2&&void 0!==arguments[2]&&arguments[2];e=e.toString();var o=this._listeners.get(e),i=null,s=0,l=r;if(Array.isArray(o))for(o.forEach(function(a,c){r||(i=n._middlewares.get(e),Array.isArray(i)?(i.forEach(function(n){n(t,function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:null;null!==e&&(t=e),s++},e)}),s>=i.length&&(l=!0)):l=!0),l&&(a.once&&(o[c]=null),a.callback(t))});-1!==o.indexOf(null);)o.splice(o.indexOf(null),1)}}]),EventEmitter}(),g=n(8),w=n.n(g),k=n(6),O=n.n(k),x=function isFunction(e){return"function"==typeof e},P=function isString(e){return"string"==typeof e||!!e&&"object"===O()(e)&&"[object String]"===Object.prototype.toString.call(e)},E=function isNode(e){try{return Node.prototype.cloneNode.call(e,!1),!0}catch(e){return!1}},S=/^(?:f(?:alse)?|no?|0+)$/i,j=function uuid(){return(arguments.length>0&&void 0!==arguments[0]?arguments[0]:"")+([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,function(e){return(e^crypto.getRandomValues(new Uint8Array(1))[0]&15>>e/4).toString(16)})},C=function detectSupportsPassive(){var e=!1;try{var t=Object.defineProperty({},"passive",{get:function get(){return e=!0,!0}});window.addEventListener("testPassive",null,t),window.removeEventListener("testPassive",null,t)}catch(e){}return e},A=function optionsFromDataset(e){var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return E(e)&&e.dataset?Object.keys(e.dataset).filter(function(e){return Object.keys(t).includes(e)}).reduce(function(t,n){return b()({},t,w()({},n,e.dataset[n]))},{}):{}};window.Node&&!Node.prototype.on&&(Node.prototype.on=function(e,t){var n=this;Array.isArray(e)||(e=e.split(" ")),e.forEach(function(e){n.addEventListener(e,t,!!C()&&{passive:!1})})}),window.NodeList&&!NodeList.prototype.on&&(NodeList.prototype.on=function(e,t){this.forEach(function(n){n.on(e,t)})}),window.Node&&!Node.prototype.off&&(Node.prototype.off=function(e,t){var n=this;Array.isArray(e)||(e=e.split(" ")),e.forEach(function(e){n.removeEventListener(e,t,!!C()&&{passive:!1})})}),window.NodeList&&!NodeList.prototype.off&&(NodeList.prototype.off=function(e,t){this.forEach(function(n){n.off(e,t)})});var q=function(e){function Component(e){var t,n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{},r=arguments.length>2&&void 0!==arguments[2]?arguments[2]:{};if(o()(this,Component),(t=a()(this,p()(Component).call(this))).element=P(e)?document.querySelector(e):e,!t.element)throw new Error("An invalid selector or non-DOM node has been provided for ".concat(t.constructor.name,"."));return t.element[t.constructor.name]=t.constructor._interface.bind(u()(t)),t.element[t.constructor.name].Constructor=t.constructor.name,t.id=j(t.constructor.name+"-"),t.options=b()({},r,n,A(t.element,r)),t}return y()(Component,e),s()(Component,null,[{key:"attach",value:function attach(){var e=this,t=arguments.length>0&&void 0!==arguments[0]?arguments[0]:null,n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{},r=new Array;if(null===t)return r;var o=function querySelectorAll(e,t){return x(e)?e(t||document):P(e)?t&&E(t)?t.querySelectorAll(e):document.querySelectorAll(e):E(e)?[e]:NodeList.prototype.isPrototypeOf(e)?e:null}(t);return[].forEach.call(o,function(o){void 0===o[e.constructor.name]?r.push(new e(o,b()({selector:t},n))):r.push(o[e.constructor.name])}),r}},{key:"_interface",value:function _interface(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{};if("string"==typeof e){if(void 0===this[e])throw new TypeError('No method named "'.concat(e,'"'));return this[e](e)}return this}}]),Component}(m),L={allowMultiple:!1};n.d(t,"default",function(){return N});var N=function(e){function bulmaCollapsible(e){var t,n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return o()(this,bulmaCollapsible),(t=a()(this,p()(bulmaCollapsible).call(this,e,n,L))).onTriggerClick=t.onTriggerClick.bind(u()(t)),t._init(),t}return y()(bulmaCollapsible,e),s()(bulmaCollapsible,[{key:"_init",value:function _init(){if(this._parent=this.element.dataset.parent,this._parent){var e=document.getElementById(this._parent);this._siblings=e.querySelectorAll(this.options.selector)||[]}this._triggers=document.querySelectorAll('[data-action="collapse"][href="#'.concat(this.element.id,'"], [data-action="collapse"][data-target="').concat(this.element.id,'"]'))||null,this._triggers&&this._triggers.on("click touch",this.onTriggerClick),this.element.classList.contains("is-active")?this.expand():this.collapse()}},{key:"destroy",value:function destroy(){this._triggers&&this._triggers.off("click touch",this.onTriggerClick,!1)}},{key:"collapsed",value:function collapsed(){return this._collapsed}},{key:"expand",value:function expand(){var e=this;(void 0===this._collapsed||this._collapsed)&&(this.emit("before:expand",this),this._parent&&!function BooleanParse(e){return!S.test(e)&&!!e}(this.options.allowMultiple)&&this._siblings.forEach(function(t){t.isSameNode(e.element)||t.bulmaCollapsible&&t.bulmaCollapsible("close")}),this.element.style.height=this.element.scrollHeight+"px",this.element.classList.add("is-active"),this.element.setAttribute("aria-expanded",!0),this._triggers&&this._triggers.forEach(function(e){e.classList.add("is-active")}),this._collapsed=!1,this.emit("after:expand",this))}},{key:"open",value:function open(){this.expand()}},{key:"collapse",value:function collapse(){void 0!==this._collapsed&&this._collapsed||(this.emit("before:collapse",this),this.element.style.height=0,this.element.classList.remove("is-active"),this.element.setAttribute("aria-expanded",!1),this._triggers&&this._triggers.forEach(function(e){e.classList.remove("is-active")}),this._collapsed=!0,this.emit("after:collapse",this))}},{key:"close",value:function close(){this.collapse()}},{key:"onTriggerClick",value:function onTriggerClick(e){e.preventDefault(),this.collapsed()?(e.currentTarget.classList.add("is-active"),this.expand()):(e.currentTarget.classList.remove("is-active"),this.collapse())}}],[{key:"attach",value:function attach(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:".is-collapsible",t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return d()(p()(bulmaCollapsible),"attach",this).call(this,e,t)}}]),bulmaCollapsible}(q)}]).default});
    |                                                                                                                                                                                                                                                      ^


  WebpackError: ReferenceError: window is not defined
  
  - bulma-collapsible.min.js:1 Object../node_modules/@creativebulma/bulma-collap    sible/dist/js/bulma-collapsible.min.js
    [lib]/[@creativebulma]/bulma-collapsible/dist/js/bulma-collapsible.min.js:1:    246
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - sync-requires.js:8 Object../.cache/sync-requires.js
    lib/.cache/sync-requires.js:8:58
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - static-entry.js:9 Module../.cache/static-entry.js
    lib/.cache/static-entry.js:9:22
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  - bootstrap:83 
    lib/webpack/bootstrap:83:1
  
  
  - universalModuleDefinition:3 webpackUniversalModuleDefinition
    lib/webpack/universalModuleDefinition:3:1
  
  - universalModuleDefinition:10 Object.<anonymous>
    lib/webpack/universalModuleDefinition:10:2
  

walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$ import { FormattedMessage } from 'react-intl';
import-im6.q16: not authorized `react-intl' @ error/constitute.c/WriteImage/1037.
walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$ import menuTree from '../data/menuTree'
import-im6.q16: not authorized `../data/menuTree' @ error/constitute.c/WriteImage/1037.
walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$ import Dropdown from '../components/DropDownMenu'
import-im6.q16: not authorized `../components/DropDownMenu' @ error/constitute.c/WriteImage/1037.
walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$ import TestMenu from '../components/TestMenu'
import-im6.q16: not authorized `../components/TestMenu' @ error/constitute.c/WriteImage/1037.
walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$ import RootMenu from '../components/RootMenu'
import-im6.q16: not authorized `../components/RootMenu' @ error/constitute.c/WriteImage/1037.
walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$ //import RootMenuMobile from '../components/RootMenuMobile'
bash: //import: File o directory non esistente
walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$ import RootMenuMobile from '../components/RootMenuMobile'
import-im6.q16: unable to grab mouse `': Risorsa temporaneamente non disponibile @ error/xwindow.c/XSelectWindow/9181.
walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$ import {
import-im6.q16: unable to grab mouse `': Risorsa temporaneamente non disponibile @ error/xwindow.c/XSelectWindow/9181.
walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$   BrowserView,
BrowserView,: comando non trovato
walter@walter-RC530-RC730:~/kalwalt-github/gatsby-starter-i18n-bulma$   MobileView,

```

**Comment by kalwalt** [comment]
i will use the [wikiki-accordion](https://wikiki.github.io/components/accordion/) instead the @creativebulma due the issue reported in a previous comment. The last commit is a simple test to check if the code works in production mode.

**Comment by kalwalt** [comment]
i will not remove the creativebulma package, maybe i can use the styling for other uses.

**Comment by kalwalt** [comment]
merging as i think i can not do more for now.

**Comment by CreativeBulma** [comment]
Hi @kalwalt,

We see you had error on compiling your project using our Collapsible component. It's strange because wikiki-accordion uses window element too.
One question: why using compiled file and not sources as you run webpack on your own side ? Maybe it will fix the issue.

don't hesitate to ask us if you need help to integrate our code. We'll be glad to help (especially if it helps to improve our code and its integration with other frameworks).

**Comment by kalwalt** [comment]
Thank you for the answer @CreativeBulma , 

> One question: why using compiled file and not sources as you run webpack on your own side ? Maybe >it will fix the issue.

Can you explain me better what do you mean with? What the difference with the two? sorry to ask this i'm not very expert with webpack...

**Comment by CreativeBulma** [comment]
A second thought tell me it will not change a thing. (I meant using raw sources : not transpiled / not minified).
I've made some change on the code based on your issue, I'll try to build your project with them and let you know.

**Comment by kalwalt** [comment]
> A second thought tell me it will not change a thing. (I meant using raw sources : not transpiled / not minified).
> I've made some change on the code based on your issue, I'll try to build your project with them and let you know.

@CreativeBulma thank you, if you want to test the project, remember that the issue raise when the project is build in production mode ( with `gatsby build `command ) and not in develop.  If you need other infos let me know!

**Comment by CreativeBulma** [comment]
Hi @kalwalt ,

do you have a slack/discord account to discuss about creativebulma/collapsible integration into your project ? If no, you can register at our own platform (I've created a channel to discuss about this topic): https://team.hexadog.com/signup_user_complete/?id=g9sjfadr8br63j7ax54ogbsqyr

First, I don't find where you're using bulma-collapsible in your source. Can you please enlight me ?
You can find

**Comment by kalwalt** [comment]
@CreativeBulma i haven't a slack account, and your link seems broken/unsafe.
I used bulma-collapsible at this commit https://github.com/kalwalt/gatsby-starter-i18n-bulma/pull/93/commits/36577f8b79d5c64a148b97800e99e6bc93b983b5

**Comment by CreativeBulma** [comment]
I can't install dependencies of your package. I got the following error:
```shell
npm WARN deprecated joi@12.0.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! Invalid dependency type requested: alias
```

**Comment by kalwalt** [comment]
Sorry, i see, probably caused by yarn.lock, delete it and also node-modules, cache and rerun `yarn install`

**Comment by CreativeBulma** [comment]
Thanks. I managed the issu by updating all dependencies to "latest" ;-)
I'm now facing the same issue as you, so I can start debugging...

**Comment by kalwalt** [comment]
> Thanks. I managed the issu by updating all dependencies to "latest" ;-)
> I'm now facing the same issue as you, so I can start debugging...

@CreativeBulma yes that was another option. Good luck and thank's again!

**Comment by CreativeBulma** [comment]
Its a classic issue with Gatsby in build process. I've integrated the basic workaround in v1.0.3.
It now build with success. Unfortunately Icouldn't fully test it with your project because even when updating <code>home.en.md</code> fil in <code>pages</code> directory the content is not displayed when serving the project.
Let me know if it's working on your side.

**Comment by kalwalt** [comment]
> Its a classic issue with Gatsby in build process. I've integrated the proposed workaround in v1.0.3.
> It now build with success. Unfortunately Icouldn't fully test it with your project because even when updating `index.en.md` file in `pages` directory the content is not displayed when serving the project.
> Let me know if it's working on your side.
@CreativeBulma  ok thank you very much! Maybe in that commit i missed something. I will test and i will inform you.

**Comment by CreativeBulma** [comment]
I forgot to mention that you have to use sources instead of transpiled - minified version of the component (due to the issue with Gatsby - the transpiled version has a <code>window</code> code added by webpack). To do this, just use the following import in your source:
```javascript
import bulmaCollapsible from '@creativebulma/bulma-collapsible/src/js/index.js'
```

**Comment by kalwalt** [comment]
@CreativeBulma thank you for this info, infact i tried with the minified version and i received the same error. I will try with the source version as you suggest.

**Comment by kalwalt** [comment]
@CreativeBulma i'm testing the latest from bulma-collapsible  #100

**Pull request merged**
