### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by MartinRosenberg**
I was having some difficulty navigating the code as is, so I figured others might be as well. I installed Prettier, configured it with what appeared to be the most common choices, and ran it. I also switched JSX files to the `.jsx` file extension to make it clear which files are just regular JS.

### CODE REVIEW

**Comment by kalwalt** [comment]
thank you @MartinRosenberg  for this! it seems that Netlify build fails for some reason i will look at when i have a bit of time.

**Comment by MartinRosenberg** [comment]
Uh oh! I know better than to submit a broken PR 😅. I'll take a look now

**Comment by MartinRosenberg** [comment]
I found the bug: I accidentally renamed some regular JS files to `.jsx`, which I fixed in https://github.com/Collabsalot/gatsby-starter-i18n-bulma/commit/9de1c054d8a885ea2252c675fa25f839707f5ca2.

The following commits are more miscellaneous improvements.

Something else I noticed is this warning:
```
warn ./src/components/OsmMap.jsx
Attempted import error: 'MapContainer' is not exported from 'react-leaflet' (imported as 'MapContainer').
```
All instructions for react-leaflet tell you to do exactly that, and MapContainer _is_ present in the [source code](https://github.com/PaulLeCam/react-leaflet/blob/master/packages/react-leaflet/src/MapContainer.tsx), so I have no idea why it's not in the package.

**Comment by MartinRosenberg** [comment]
Something else I noticed is this warning:
```
warn ./src/components/OsmMap.jsx
Attempted import error: 'MapContainer' is not exported from 'react-leaflet' (imported as 'MapContainer').
```
All instructions for react-leaflet tell you to do exactly that, and MapContainer _is_ present in the [source code](https://github.com/PaulLeCam/react-leaflet/blob/master/packages/react-leaflet/src/MapContainer.tsx), so I have no idea why it's not in the package.

**Comment by MartinRosenberg** [comment]
Update to that last comment: `MapContainer` is apparently in react-leaflet **v3** and you're using **v2**. I'm not familiar with the library, so I'll leave it to you to either make the major version upgrade, or make the changes to use v2.

**Comment by MartinRosenberg** [comment]
https://github.com/kalwalt/gatsby-starter-i18n-bulma/pull/149/commits/4e73035b4a4aef936ecf3e84eb16ce2f80bfd726 might close #131 if it's still a problem

**Comment by kalwalt** [comment]
Thank you @MartinRosenberg to fix the Netlify build! in regards the `MapContainer` issue, I think  i had to use an older react-leaflet version because the plugin didn't support a newer gatsby version, but maybe there are some news in this sense and this can be fixed.

**Comment by kalwalt** [comment]
I tested locally and i think should be ok. To be honest there are other small issues, but i think they go out of this scope. I will open separate issues for them. If you are ok i can merge it.

**Comment by MartinRosenberg** [comment]
Yeah, there isn't really a scope here per se. The `MapContainer` thing e.g. is just a thing that I noticed, but not something I was trying to fix and I should've just made it an Issue instead of mentioning it here 😅. I'm happy for you to merge it at any point, but definitely let me know if you found problems with anything I did!

**Comment by kalwalt** [comment]
Thank you @MartinRosenberg for your contribution!

**Pull request merged**
